version: '2'
services:

    api-gate:
        build: gateway
        image: api-gate
        expose:
            - "8000"
        restart: always

    proxy:
        build: gateway-proxy
        image: proxy
        expose:
            - "80"
        ports:
            - "80:80"
        restart: always
        depends_on:
            - api-gate
