sudo: required
dist: trusty
env:
    - MOZ_HEADLESS=1
addons:
    chrome: stable
    firefox: latest
language: python3
python:
    - "3.6"

services:
    - docker

before_install:
    - curl https://bootstrap.pypa.io/get-pip.py > get-pip.py
    - sudo python3 get-pip.py
    - sudo pip3 install -r requirements.txt
    - sudo rm -f get-pip.py
    - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 &
    - sudo /bin/bash testing/get-webdrivers.sh
    - docker-compose up -d

script:
    # Check code style
    - pycodestyle --ignore=E402 $(find . -name "*.py")

    # Check if all the docker images are up
    - docker ps | grep frontend -q
    - docker ps | grep front-proxy -q
    - docker ps | grep api-gate -q
    - docker ps | grep proxy -q
    - docker ps | grep user-db -q

    # Run load balance checks
    - python3 testing/locust_check.py

    # Run browser functionality checks
    - python3 testing/selenium-test.py
