sudo: required

language: python3
python:
    - "3.6"

services:
    - docker

before_install:
    - curl https://bootstrap.pypa.io/get-pip.py > get-pip.py
    - sudo python3 get-pip.py
    - sudo pip3 install locust
    - docker-compose up -d

script:
    # Check code style
    - pycodestyle $(find . -name "*.py")

    # Check if all the docker images are up
    - docker ps | grep frontend -q
    - docker ps | grep front-proxy -q
    - docker ps | grep api-gate -q
    - docker ps | grep proxy -q
    - docker ps | grep user-db -q

    # Run load balance checks
    - python3 testing/locust_check.py

    # Run browser functionality checks
    - python3 testing/selenium-test.py
