version: '2'
services:

    user-db:
        build: user-database
        image: user-db
        expose:
            - "3306"
        restart: always

    frontend:
        build: frontend/app
        image: frontend
        command: uwsgi --ini ui.ini
        expose:
            - "8000"
        ports:
            - "8000:8000"
        restart: always

    front-proxy:
        build: frontend/proxy
        image: front-proxy
        expose:
            - "8000"
        restart: always
        depends_on:
            - frontend

    auth:
        build: authenticate-server
        image: auth
        expose:
            - "8080"
        restart: always
        depends_on:
            - frontend

    api-gate:
        build: api-gateway/gateway
        image: api-gate
        expose:
            - "8000"
        restart: always

    proxy:
        build: api-gateway/gateway-proxy
        image: proxy
        expose:
            - "80"
        ports:
            - "80:80"
        restart: always
        depends_on:
            - api-gate

    skits-controller:
        build: skits-controller
        image: skits-controller
        expose:
            - "8080"
        restart: always
        depends_on:
            - kibana
            - elasticsearch

    elasticsearch:
        build: skits-elasticsearch/elasticsearch
        image: es
        expose:
            - "9200"
        restart: always
        depends_on:
            - frontend

    kibana:
        build: skits-elasticsearch/kibana
        image: kibana
        expose:
            - "5601"
        ports:
            - "5601:5601"
        restart: always
        depends_on:
            - elasticsearch
