version: '2'
services:

    frontend:
        build: frontend
        image: frontend
        command: uwsgi --ini ui.ini
        expose:
            - "8000"
        restart: always

    api-gate:
        build: api-gateway/gateway
        image: api-gate
        expose:
            - "8000"
        restart: always

    proxy:
        build: api-gateway/gateway-proxy
        image: proxy
        expose:
            - "80"
        ports:
            - "80:80"
        restart: always
        depends_on:
            - api-gate
